//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaESDO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemaESDOEntities : DbContext
    {
        public sistemaESDOEntities()
            : base("name=sistemaESDOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direccionesData> direccionesData { get; set; }
        public virtual DbSet<estadoTurnoData> estadoTurnoData { get; set; }
        public virtual DbSet<horariosData> horariosData { get; set; }
        public virtual DbSet<PasswordResetTokens> PasswordResetTokens { get; set; }
        public virtual DbSet<profesionalesData> profesionalesData { get; set; }
        public virtual DbSet<tipoTurnosData> tipoTurnosData { get; set; }
        public virtual DbSet<turnosData> turnosData { get; set; }
        public virtual DbSet<turnosTempData> turnosTempData { get; set; }
        public virtual DbSet<usuarioData> usuarioData { get; set; }
        public virtual DbSet<usuarioRolData> usuarioRolData { get; set; }
    }
}
