//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaESDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnosTempData
    {
        public int turTempID { get; set; }
        public string turTempNombre { get; set; }
        public string turTempApellido { get; set; }
        public string turTempEmail { get; set; }
        public string turTempTelefono { get; set; }
        public Nullable<System.DateTime> turTempFecha { get; set; }
        public string turTempMensaje { get; set; }
        public Nullable<int> turTempTipoTurno { get; set; }
        public Nullable<int> turTempHorario { get; set; }
    }
}
