//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaESDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioData
    {
        public int userID { get; set; }
        public string userNombre { get; set; }
        public string userApellido { get; set; }
        public string userEmail { get; set; }
        public string userContrasena { get; set; }
        public Nullable<int> userRolID { get; set; }
    
        public virtual usuarioRolData usuarioRolData { get; set; }
    }
}
