//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaESDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioRolData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarioRolData()
        {
            this.usuarioData = new HashSet<usuarioData>();
        }
    
        public int rolID { get; set; }
        public string rolNombre { get; set; }
        public Nullable<int> rolPoder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioData> usuarioData { get; set; }
    }
}
